version: '3'

services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
      - C:\\Users\\bella\\dev\\docker\\volumes\\PostgreSQL\\var\\lib\\postgresql\\data:/var/lib/postgresql/data
    networks:
      - postgres-ebac-network

  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bellacabral80@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

  ebac-mysql-compose:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: 'mod_36_mysql'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - "3307:3306"

networks:
  postgres-ebac-network:
    driver: bridge
